let store = {
  _state: {
    cards: [
      {
        id: 1234,
        exclusive: false,
        liked: false,
        onSale: true,
        type: "",
        newBuilt: false,
        location: {},
        price: 150000,
        area: 36,
        rooms: 2,
        structure: "",
        restoration: false,
        floor: 4,
        date: "24.07",
      },
      {
        id: 32432,
        exclusive: false,
        liked: true,
        onSale: false,
        type: "",
        newBuilt: true,
        location: {},
        price: 200000,
        area: 22,
        rooms: 1,
        structure: "",
        restoration: true,
        floor: 3,
        date: "24.07",
      },
      {
        id: 2342435,
        exclusive: false,
        liked: true,
        onSale: false,
        type: "",
        newBuilt: true,
        location: {},
        price: 250000,
        area: 56,
        rooms: 4,
        structure: "",
        restoration: true,
        floor: 5,
        date: "24.07",
      },
      {
        id: 13213013,
        exclusive: false,
        liked: true,
        onSale: true,
        type: "",
        newBuilt: true,
        location: {},
        price: 250000,
        area: 56,
        rooms: 4,
        structure: "",
        restoration: true,
        floor: 2,
        date: "24.07",
      },
      {
        id: 32432,
        exclusive: false,
        liked: false,
        onSale: false,
        type: "",
        newBuilt: true,
        location: {},
        price: 200000,
        area: 22,
        rooms: 5,
        structure: "",
        restoration: true,
        floor: 3,
        date: "24.07",
      },
    ],
  },
  getState() {
    return this._state;
  },
};
export default store;
